agent0ai/agent-zero

- python/helpers/log.py
On Win10 x64 and other pltf the UI does not run without this fix.
> Quick fix log.py

- python/helpers/settings.py
- run_ui.py
- webui/index.css
- webui/index.html
- webui/index.js
missing
- image attachment
- work_dir browser (backend implemented, WIP)
- WHISPER (hurry up)
> UI Knowledge import, attachments, voice input and scroll fix

- agent.py
- python/extensions/message_loop_prompts/_30_include_attachments.py
- python/helpers/voice_transcription.py
- requirements.txt
- run_ui.py
- webui/index.css
- webui/index.js
- webui/messages.js
- webui/settings.css
Voice input :-)
- Click the mic button to start recording
- The message is sent automatically to A0 when silence (customizable) is detected
- You can stop the mic manually if you want
- Uses openai-whisper
- Supports hybrid (keyboard + voice input)
> feature: openai-whisper voice input

- webui/css/file_browser.css
- webui/css/history.css
- webui/css/modals.css
- webui/css/settings.css
- webui/css/toast.css
- webui/index.css
- webui/index.html
- webui/index.js
- organized structure
- consolidated selectors and states
- improved page speed
- new modern toasts (color and text change dinamically without a new toast appearing) :)
> CSS refactor and toasts

- webui/css/toast.css
- webui/index.css
- webui/index.js
`toast.css` and `index.js`
- fixed toasts disappearing right after showing
- simplified toast animation
`index.css`
- set 2ⁿᵈ mobile breakpoint at 640px
> fix: toast handling, mobile breakpoint

- webui/css/modals.css
- webui/css/settings.css
- webui/index.css
- webui/index.html
- webui/js/modal.js
- fullscreen button for chat input
- some css fixes here and there
> feature: fullscreen chat input

- agent.py
- initialize.py
- prompts/default/agent.system.tools_vision.md
- prompts/default/fw.tool_result.md
- python/extensions/system_prompt/_10_system_prompt.py
- python/helpers/history.py
- python/helpers/settings.py
- python/helpers/tool.py
If chat model is configured to support vision (capable of vision), then the message attachment images are being presented to the model with the message.
> feat: chat model VISION support for user and tool msg attachments

- models.py
- python/helpers/settings.py
This pull request introduces support for a new model provider, "Chutes," by adding relevant configurations, API key handling, and methods for chat and embedding functionality. The most important changes are grouped into model provider updates, API key handling, and new functionality for Chutes.
* Added "Chutes" to the `ModelProvider` enum in `models.py` to recognize it as a valid model provider.
* Updated the `get_api_key` function in `models.py` to support fetching `CHUTES_API_TOKEN` from environment variables.
* Added a new entry for "Chutes API Key" in the `convert_out` function in `settings.py` to include it in the API keys section of the settings output.
* Introduced `get_chutes_chat` and `get_chutes_embedding` functions in `models.py` to handle chat and embedding operations for …
> chutes llm provider

- prompts/default/agent.system.tool.scheduler.md
- python/helpers/task_scheduler.py
- python/tools/scheduler.py
This allows for task delegation and result retrieval by agent zero making the scheduler orchestrable.
> Scheduler wait_for_task and find_task_by_name

- prompts/default/agent.system.tool.response.md
- webui/js/messages.js
- Updated system prompt to encourage markdown usage.
- Implemented markdown rendering for response bubbles.
> Render markdown in agent responses

- python/helpers/settings.py
Fixed Whisper Large model label from **Large (1.5B, Multilingual)** to **Large (1.5G, Multilingual)**
> fix Whisper model typo

- python/helpers/settings.py
> Revert "fix Whisper model typo"

- prompts/default/agent.system.main.solving.md
- prompts/default/agent.system.main.tips.md
- prompts/default/agent.system.tool.call_sub.md
- prompts/default/agent.system.tool.call_sub.py
- prompts/default/agent.system.tool.knowledge.md
- prompts/developer/agent.system.main.communication.md
- prompts/developer/agent.system.main.developer.md
- prompts/developer/agent.system.main.environment.md
- prompts/developer/agent.system.main.md
- prompts/developer/agent.system.main.role.md
- prompts/meta.json
- prompts/research_agent/agent.system.main.communication.md
- prompts/research_agent/agent.system.main.deep_research.md
- prompts/research_agent/agent.system.main.role.md
- python/helpers/files.py
- python/tools/call_subordinate.py
This PR updates some of the already present prompts, adds prompt folder for developer agent and implements prompt variable plugins that can dynamically load variables into template with arbitrary logic.
> Prompt Profiles for subordinate agent, prompt plugins, developer agent prompts

- docs/mcp_setup.md
- python/helpers/mcp_handler.py
- tests/mcp/stream_http_mcp_server.py
- tests/mcp/stream_http_mcp_server_README.md
- tests/mcp/stream_http_mcp_server_requirements.txt
This PR adds support for connecting streamable-http mcp servers in addition to stdio and sse.
> Add support for 'streamable-http' transport MCP servers

- docker/run/docker-compose.yml
- python/api/image_get.py
- webui/components/chat/attachments/attachmentsStore.js
- webui/components/chat/attachments/dragDropOverlay.html
- webui/components/chat/attachments/imageModal.html
- webui/index.css
- webui/index.html
- webui/index.js
- webui/js/AlpineStore.js
- webui/js/initFw.js
- webui/js/messages.js
- webui/js/tunnel.js
- **Centralized Attachment Store**: Created Alpine.js store pattern following existing codebase conventions
- **Component Extraction**: Modularized drag-drop overlay into reusable component system
- **Logic Migration**: Moved ~70 lines of attachment logic from `index.js` to centralized store
- **State Management**: Unified attachment state with proper Alpine.js integration
- **Drag & Drop**: Improved file handling with visual feedback and counter-based overlay control
- **Clipboard Pasting**: Smart image paste detection with GUID-based filename generation
- **Modal Viewing**: Image modal with zoom controls (−/⌂/+) and clean design
- **Duplicate Prevention**: Fixed bug where re-adding same attachments would fail silently
- **Server-Side URLs**: Fixed blob URL issues by implementing …
> 🎯 Enhanced Attachment System for Agent Zero Chat Interface - #5

- preload.py
- python/api/synthesize.py
- python/helpers/kokoro_tts.py
- python/helpers/settings.py
- requirements.txt
- run_ui.py
- webui/index.html
- webui/index.js
- webui/js/initFw.js
- webui/js/settings.js
- webui/js/speech-store.js
- webui/js/speech.js
- webui/public/speech.svg
- Added Kokoro TTS support in preload and run_ui scripts.
- Introduced a new API endpoint for text-to-speech synthesis.
- Updated settings to include TTS enable/disable option.
- Refactored speech handling to utilize a centralized speech store.
- Enhanced UI with new speech button and SVG icon.
- Updated dependencies in requirements.txt for Kokoro TTS.
Docker Image Size Impact
- Current: ~9.17 GB
- Addition: ~400-450 MB (4-5% increase)
- Kokoro model: ~350 MB (or 80 MB if quantized)
- Dependencies: ~50-100 MB
Memory Consumption Impact
- Base memory: +80-150 MB when model is loaded
- Active TTS: +200-400 MB during audio generation
- Peak usage: +500-600 MB during heavy TTS workloads
Key Optimizations Already in Place
1. Lazy loading - model only loads on first TTS request
2. Single …
> Kokoro-tts

- prompts/default/agent.system.tool.memory.md
- prompts/default/memory.consolidation.sys.md
- prompts/default/memory.keyword_extraction.sys.md
- python/api/import_knowledge.py
- python/extensions/message_loop_prompts_after/_50_recall_memories.py
- python/extensions/message_loop_prompts_after/_51_recall_solutions.py
- python/extensions/monologue_end/_50_memorize_fragments.py
- python/extensions/monologue_end/_51_memorize_solutions.py
- python/helpers/knowledge_import.py
- python/helpers/memory.py
- python/helpers/memory_consolidation.py
- python/tools/knowledge_tool._py
- run_tests.py
- tests/memory_consolidation/TESTING.md
- tests/memory_consolidation/TEST_ANALYSIS.md
- tests/memory_consolidation/TEST_ISOLATION.md
- tests/memory_consolidation/test_memory_consolidation.py
This PR implements memory consolidation by merging complementary memories, replacing/updating.
Should lead to a more consistent and recent memory state
> feat: Implement Memory Consolidation (Update/Replace/Merge)

- conf/model_providers.yaml
- initialize.py
- models.py
- preload.py
- python/helpers/memory.py
- python/helpers/providers.py
- python/helpers/settings.py
- Add conf/model_providers.yaml with structured provider definitions
- Create providers.py helper for dynamic provider management  
- Update models.py to use provider-specific config defaults
- Modify settings.py to load provider options from YAML config
- Enables easier management of supported providers without code changes
> Model providers refactor + Venice AI

- agent.py
- prompts/default/fw.initial_message.md
- python/extensions/agent_init/_10_initial_message.py
> feat: initial message in chat

- python/api/get_work_dir_files.py
- python/helpers/file_browser.py
This skips not accessible files instead of showing empty directory.
It also limits entries to 10000 files and folders.
> File browser fix directory listing

- python/helpers/mcp_server.py
- webui/components/settings/mcp/server/example.html
This adds streamable http mcp server to A0
> Streamable HTTP MCP server impl

- agent.py
- prompts/agent.system.tool.a2a_chat.md
- python/helpers/fasta2a_client.py
- python/helpers/fasta2a_server.py
- python/helpers/mcp_server.py
- python/helpers/settings.py
- python/tools/a2a_chat.py
- requirements.txt
- run_ui.py
- test_fasta2a_client.py
- webui/components/settings/external/a2a-connection.html
- webui/js/settings.js
- webui/public/a2a_server.svg
FastA2A Based implementation of agent card and a2a client/server.
> A2A Client/Server Implementation

- webui/index.html
- webui/js/manifest.json
- webui/public/icon-maskable.svg
- webui/public/icon.svg
This pull request adds Progressive Web App (PWA) support to the project.
The following changes were made:
•	Added a manifest.json file and linked it in the <head> section to define app metadata (name, icons, theme color, etc.).
•	Implemented a Service Worker (sw.js) and registered it in the <body> to enable offline capability and caching.
•	Ensured that the application can now be installed as a PWA on supported browsers (e.g., Chrome, Edge, Arc).
With this update, users will be able to install the app to their devices and enjoy a more native-like experience, including offline access and faster loading.
> Implement Progressive Web App (PWA) installation support

- python/helpers/mcp_handler.py
This patch adds an option to be able to pass a `verify` option to MCP servers definition. It is set to true by default which means that TLS certificate are being checked like they were before the patch if unset. If set to `false` then the TLS certificate are not checked.
This option is really useful to have agent zero work with MCP servers on internal network where it is difficult to have public and valid certificate.
It was necessary to update the MCP python module to get access to an option allowing to pass custom HTTP client.
> new option for mcp servers

- webui/components/settings/memory/memory-dashboard.html
- webui/components/settings/memory/memory-detail-modal.html
- webui/css/modals.css
- webui/css/modals2.css
- webui/css/settings.css
Complete UI redesign and CSS optimization of the memory dashboard component, reducing code complexity by 40% while improving visual consistency and user experience.
- Aligned and organized all UI elements in both desktop and mobile views
- Unified styling with existing global CSS classes and variables as much as possible
- Fixed dark/light theme inconsistencies using CSS variables
- Reduced CSS by ~700 lines (40% reduction)
- Leveraged existing global classes (`.btn`, `.modal-header`, `.modal-footer`, etc.)
- Implemented dynamic footer injection for the Export button to ensure it remains visible. This is because the dashboard uses the newer component system and the modal helper called (`/webui/js/modals.js`) is not modal.js (without the 's' used by other modals, including Settings) which …
> feat: memory dashboard UI design and CSS optimization

- webui/components/settings/memory/memory-detail-modal.html
- webui/js/modals.js
- guard for modal-inner and propagation to modal-body
- CSS polishing for the memory detail component
> feat: modal body fix, mem-detail CSS polishing
